library-notifygru.notifier.email.enabled=true
library-notifygru.notifier.broadcastEmail.enabled=false
library-notifygru.notifier.statistics.enabled=false
library-notifygru.notifier.notificationStore.enabled=false

library-notifygru.NotificationStoreNotifierService.notificationEndPoint=http://localhost:9092/lutece/rest/notification/send
library-notifygru.NotificationStoreNotifierService.apiManagerEndPoint=http://localhost:9092/lutece/rest/api/token
library-notifygru.NotificationStoreNotifierService.apiManagerCredentials=CHANGE_ME